### ISSUE TITLE
Incorrect SQL Query in nrfident.py

### ISSUE THREAD

**Issue by DrSchottky** [DigitalSecurity/nrf5x-tools#3]
Hi,
I think that [this query](https://github.com/DigitalSecurity/nrf5x-tools/blob/ca72860ed186ee6d510340fdadcd787714b1de5f/nrfident.py#L44) is incorrect: it should be `select sdk_version, softdevice_v from ...` since `softdevice_v`  is used [here](https://github.com/DigitalSecurity/nrf5x-tools/blob/ca72860ed186ee6d510340fdadcd787714b1de5f/nrfident.py#L78)

**Comment by lychnis42** [comment]
Thank you for the report. It is fixed !
