### ISSUE TITLE
Parser cant get SDK 14.2.0

### ISSUE THREAD

**Issue by eybisi** [DigitalSecurity/nrf5x-tools#4]
Some SDK files cant be parsed by nrfparse.py
After extracting zip, parser needs folders in that directory. But for example developer.nordicsemi.com/nRF5_SDK/nRF5_SDK_v14.x.x/nRF5_SDK_14.2.0_17b948a.zip  contains nRF5_SDK_14.2.0_17b948a folder. So it cant parse that SDK.

**Comment by palmerc** [comment]
This is actually true of all firmwares starting around that time going forward.
